export enum GENERIC_PATH {
  MANAGEMENT = "/management",
  AUTH = "/auth",
  LOGIN = "/login",
  REGISTER = "/register",
  HOME = "/",
  PRODUCT = "/product",
  PROFILE = "/profile",
  CONTACT = "/contact",
  ABOUT_US = "/about-us",
  WARRANTY_POLICY = "warranty-policy",
  RETURN_POLICY = "return-policy",
  PAYMENT_AND_DELIVERY_METHODS = "payment-and-delivery-methods",
  BRAND = "/brand",
  CART = "/cart",
  USER = "/user",
  ORDER = "/order",
  PICKLIST = "/picklist",
  UPLOAD = "/upload",
}
